#!/bin/sh
# FIREWALL GRUPO 4
#SO2A - 2019
clear
echo -e "\n\t\t\t\tFIREWALL GRUPO 4"
echo -e "\t\t\t\t  SO1A - 2018\n"

#SE LIMPIAN LAS CONFIGURACIONES ANTERIORES QUE PUEDAN EXISTIR
echo -e "LIMPIANDO CONFIGURACIONES..."
iptables -F 
iptables -X
iptables -Z
iptables -t nat -F

#SE COLOCAN LAS CONFIGURACIONES INICIALES O GENERALES
echo -e "CONFIGURACIONES BASICAS..."
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -t nat -P PREROUTING ACCEPT
iptables -t nat -P POSTROUTING ACCEPT

#SE CIERRAN LAS ENTRADAS POR LOS PUERTOS QUE NO SE UTILIZARAN
echo -e "ABRIENDO PUERTOS A CLIENTES..."
iptables -A INPUT -s 192.168.1.42 -p tcp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.1.42 -p udp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.1.42 -p tcp --dport 10000 -j ACCEPT
iptables -A INPUT -s 192.168.1.42 -p tcp --dport 3306 -j ACCEPT
iptables -A INPUT -s 192.168.50.66 -p tcp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.50.66 -p udp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.50.66 -p tcp --dport 10000 -j ACCEPT
iptables -A INPUT -s 192.168.50.66 -p tcp --dport 3306 -j ACCEPT
iptables -A INPUT -s 192.168.1.65 -p tcp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.1.65 -p udp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.1.65 -p tcp --dport 10000 -j ACCEPT
iptables -A INPUT -s 192.168.1.65 -p tcp --dport 3306 -j ACCEPT
iptables -A INPUT -s 192.168.43.95 -p tcp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.43.95 -p udp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.43.95 -p tcp --dport 10000 -j ACCEPT
iptables -A INPUT -s 192.168.43.95 -p tcp --dport 3306 -j ACCEPT
iptables -A INPUT -s 192.168.43.100 -p tcp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.43.100 -p udp --dport 1:1024 -j ACCEPT
iptables -A INPUT -s 192.168.43.100 -p tcp --dport 10000 -j ACCEPT
iptables -A INPUT -s 192.168.43.100 -p tcp --dport 3306 -j ACCEPT


#SE CONCEDE ACCESO TOTAL A LAS MAUQUINAS DEL GRUPO
echo -e "CONCEDIENDO ACCESO A MAQUINAS INTERNAS..."
iptables -A INPUT -s 192.168.1.42 -j ACCEPT
iptables -A FORWARD -s 192.168.1.42 -j ACCEPT
iptables -A INPUT -s 192.168.50.66 -j ACCEPT
iptables -A FORWARD -s 192.168.50.66 -j ACCEPT
iptables -A INPUT -s 192.168.1.65 -j ACCEPT
iptables -A FORWARD -s 192.168.1.65 -j ACCEPT
iptables -A INPUT -s 192.168.43.95 -j ACCEPT
iptables -A FORWARD -s 192.168.43.95 -j ACCEPT
iptables -A INPUT -s 192.168.43.100 -j ACCEPT
iptables -A FORWARD -s 192.168.43.100 -j ACCEPT


#SE CIERRAN LAS ENTRADAS POR LOS PUERTOS QUE NO SE UTILIZARAN
echo -e "CERRANDO PUERTOS..."
iptables -A INPUT -s 0.0.0.0/0 -p tcp --dport 1:1024 -j DROP
iptables -A INPUT -s 0.0.0.0/0 -p udp --dport 1:1024 -j DROP
iptables -A INPUT -s 0.0.0.0/0 -p tcp --dport 10000 -j DROP
iptables -A INPUT -s 0.0.0.0/0 -p tcp --dport 3306 -j DROP

#DENEGANDO ACCESOS A MAQUINA AJENAS AL GRUPO
echo -e "DENEGANDO EL RESTO DE ACCESOS..."
iptables -A INPUT -s 0.0.0.0/0 -j DROP
iptables -A FORWARD -s 0.0.0.0/0 -j DROP

#SE ENMASCARA CUALQUIER IP SALIENTE CON UNA PUBLICA
#echo -e "ENMASCARAMIENTO..."
#echo 1 > /proc/sys/net/ipv4/ip_forward
#iptables -t nat -A POSTROUTING -s 192.168.50.0/0 -o wlp1s0 -j MASQUERADE

echo -e "\n\t\t\t\t     LISTO\n\n"
iptables -L -n
echo -e "\n"
